source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GEImagePicker_Example', :exclusive => true do
  pod 'GEImagePicker', :path => '../'
end

target 'GEImagePicker_Tests', :exclusive => true do
  pod 'GEImagePicker', :path => '../'

  
end
